In [63]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler 
from sklearn.decomposition import PCA

In [64]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

matrix = StandardScaler().fit_transform(matrix)

U, S, Vt = np.linalg.svd(matrix)

In [59]:
matrix

array([[-1.34164079, -1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079,  1.34164079]])

In [30]:
U

array([[-6.70820393e-01,  7.40013004e-01, -4.87929773e-02,
        -2.31872909e-17],
       [-2.23606798e-01, -1.59740744e-01,  6.51523518e-01,
         7.07106781e-01],
       [ 2.23606798e-01,  1.59740744e-01, -6.51523518e-01,
         7.07106781e-01],
       [ 6.70820393e-01,  6.33519174e-01,  3.85556035e-01,
         4.36724750e-16]])

In [31]:
S

array([3.46410162e+00, 2.93749601e-16, 1.84297753e-33])

In [54]:
Vt

array([[ 0.57735027,  0.57735027,  0.57735027],
       [-0.81649658,  0.40824829,  0.40824829],
       [ 0.        , -0.70710678,  0.70710678]])

In [60]:
S_matrix = np.zeros((U.shape[1], Vt.shape[0]))
np.fill_diagonal(S_matrix, S)

In [55]:
S_matrix

array([[3.46410162e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.93749601e-16, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.84297753e-33],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [62]:
np.dot(np.transpose(matrix), matrix) / (matrix.shape[0] - 1)

array([[1.33333333, 1.33333333, 1.33333333],
       [1.33333333, 1.33333333, 1.33333333],
       [1.33333333, 1.33333333, 1.33333333]])

In [66]:
cov_matrix = np.cov(matrix, rowvar=False)
print(cov_matrix)

[[1.33333333 1.33333333 1.33333333]
 [1.33333333 1.33333333 1.33333333]
 [1.33333333 1.33333333 1.33333333]]


In [67]:
matrix_centered = matrix - np.mean(matrix, axis=0)

# 2. Računanje matrice kovarijanse ručno
cov_matrix_manual = np.dot(matrix_centered.T, matrix_centered) / (matrix.shape[0] - 1)

# 3. Računanje matrice kovarijanse korišćenjem numpy funkcije
cov_matrix_numpy = np.cov(matrix, rowvar=False)

print("Manually calculated covariance matrix:\n", cov_matrix_manual)
print("Numpy covariance matrix:\n", cov_matrix_numpy)

Manually calculated covariance matrix:
 [[1.33333333 1.33333333 1.33333333]
 [1.33333333 1.33333333 1.33333333]
 [1.33333333 1.33333333 1.33333333]]
Numpy covariance matrix:
 [[1.33333333 1.33333333 1.33333333]
 [1.33333333 1.33333333 1.33333333]
 [1.33333333 1.33333333 1.33333333]]


In [51]:
U_cut = U[:, :1]
S_cut = S_matrix[:1, :1]
Vt_cut = Vt[:1, :]

In [52]:
np.dot(U_cut, S_cut)

array([[-2.32379001],
       [-0.77459667],
       [ 0.77459667],
       [ 2.32379001]])

In [35]:
np.dot(np.dot(U_cut, S_cut), Vt_cut)

array([[-1.34164079, -1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079,  1.34164079]])

In [25]:
frobenius_norm_difference = np.linalg.norm((matrix - np.dot(np.dot(U_cut, S_cut), Vt_cut)))

In [26]:
frobenius_norm_difference

1.2906616757612317

In [47]:
pca = PCA(n_components=1)
pca.fit_transform(matrix)

array([[-2.32379001],
       [-0.77459667],
       [ 0.77459667],
       [ 2.32379001]])